#' initialize the logger
#'
#' This function initializes the futile.logger. It is used internally and
#' shouldn't be called by users.
#'
#' @param config the config object generated by reading the decorated comments
#'
initialize_logger <- function(config) {

  log_dir <- file.path("~", "scheduler", "log")

  if(!dir.exists(log_dir)) {
    dir.create(log_dir, recursive = TRUE)
  }
  if(interactive()) {
    futile.logger::flog.appender(
      futile.logger::appender.tee(file.path(log_dir, paste0(gsub(" ", "_", config$name), ".txt")))
    )
  } else {
    futile.logger::flog.appender(
      futile.logger::appender.file(file.path(log_dir, paste0(gsub(" ", "_", config$name), ".txt")))
    )
  }

  flog.threshold(config$log)

  return(config)

}
